---
version: '3'
services:
  minio:
    image: minio/minio
    ports:
      - 9000:9000
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - "minio_data:/data"
    command: server --console-address ":9001" /data

  init-minio:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc config host add myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/local-warehouse
      "
  dagster-db:
    image: postgres:15-alpine
    volumes:
      - dagster_db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=warehouse
    ports:
      - 5432:5432

volumes:
  dagster_db_data:
  minio_data:
